### ISSUE TITLE
opensource_model.pth.tar may be not available.

### ISSUE THREAD

**Issue by sidabit** [HKUST-Aerial-Robotics/MVDepthNet#23]
Hi Kai-Xuan,

The trained model file opensource_model.pth.tar seems not accessible on the dropbox, while the sample dataset is available to download.

Sida
![screenshot](https://user-images.githubusercontent.com/37279113/69855433-7260ea00-12c6-11ea-9c03-bcfb9c5d7b91.png)

**Comment by WANG-KX** [comment]
Seems fine on my side.
Can't download?

**Comment by djjandXMU** [comment]
I can not unzip the opensource_model.pth,it seems that it maybe a damaged file.
But the sample_data.pkl.tar is ok

**Comment by WANG-KX** [comment]
Hi, the uploaded wight file does not need to be extracted before loading. Just load *.pth.tar is fine.

**Comment by sidabit** [comment]
> Hi, the uploaded wight file does not need to be extracted before loading. Just load *.pth.tar is fine.

Hi, Kaixuan. Thanks a lot. It works right now.

**Comment by djjandXMU** [comment]
Thanks for your help,it works!

**Comment by DejaYang** [comment]
Hi, when I ran 'python example.py',  there was one error, 
`
Traceback (most recent call last):
  File "example.py", line 62, in <module>
    predict_depths = depthnet(left_image_cuda, right_image_cuda, KRKiUV_cuda_T, KT_cuda_T)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emg/code_yj/stereo_code/MVDepthNet-master/depthNet_model.py", line 173, in forward
    conv1 = self.conv1(x)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/emg/miniconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'padding' must be tuple of ints, but found element of type float at pos 1
`
Do you know how to solve this problem?
